// <auto-generated />
using System;
using MailsService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MailsService.Data.Migrations
{
    [DbContext(typeof(MailsServiceDbContext))]
    partial class MailsServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MailsService.Model.Entities.SentReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SentReport");
                });

            modelBuilder.Entity("MailsService.Model.Entities.SentReport", b =>
                {
                    b.OwnsOne("MailsService.Model.Entities.AuditMessageStatus", "MessageStatus", b1 =>
                        {
                            b1.Property<int>("SentReportId")
                                .HasColumnType("int");

                            b1.Property<string>("FailedMassage")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("FailedMassage");

                            b1.Property<string>("Result")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Result");

                            b1.Property<DateTime>("SentDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("SentDate");

                            b1.HasKey("SentReportId");

                            b1.ToTable("SentReport");

                            b1.WithOwner()
                                .HasForeignKey("SentReportId");
                        });

                    b.OwnsOne("MailsService.Model.Entities.Message", "Message", b1 =>
                        {
                            b1.Property<int>("SentReportId")
                                .HasColumnType("int");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("Body");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Subject");

                            b1.HasKey("SentReportId");

                            b1.ToTable("SentReport");

                            b1.WithOwner()
                                .HasForeignKey("SentReportId");
                        });

                    b.OwnsOne("MailsService.Model.Entities.Recipient", "Recipient", b1 =>
                        {
                            b1.Property<int>("SentReportId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(260)
                                .HasColumnType("nvarchar(260)")
                                .HasColumnName("Recipient");

                            b1.HasKey("SentReportId");

                            b1.ToTable("SentReport");

                            b1.WithOwner()
                                .HasForeignKey("SentReportId");
                        });

                    b.Navigation("Message");

                    b.Navigation("MessageStatus");

                    b.Navigation("Recipient");
                });
#pragma warning restore 612, 618
        }
    }
}
